# Generated by Django 5.1.2 on 2026-05-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_clientsubscription_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
