# Generated by Django 5.1.2 on 2026-06-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_must_change_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="must_change_password",
        ),
    ]
